apiVersion: v1
kind: Service
metadata:
  name: hello-world-nodeport-service
spec:
  type: NodePort
  selector:
    app: hello-world-50000
  ports:
  - protocol: TCP
    port: 80
    targetPort: 50000
