---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: test-mapping
      prefix: /
      service: test-service
      host_rewrite: test-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
  selector:
    app: microservice-deployment
